[project]
name = "mcp-opentofu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.11.3",
    "pydantic-ai>=0.2.3",
]

[dependency-groups]
dev = [
    "pyright>=1.1.404",
    "ruff>=0.11.9",
]
